### ISSUE TITLE
Clean Documentation 

### ISSUE THREAD

**Issue by p1utoze** [p1utoze/bookmark_backup#5]
This tool/web extension is used for saving bookmarks externally in case of browser failures(especially Brave Browser with lack of auto-save bookmarks to an account or on local device). It is built purely on python which reads bookmarks file from browsers and saves a clean-formatted bookmark file and display on webpage.

**Comment by the-amazing-atharva** [comment]
Hi
I am a beginner here and found your repository while searching for issues

I would like to contribute to the README.md file of this repo

I would like to be assigned to this issue and I will send a PR in sometime

**Comment by p1utoze** [comment]
Sure! You can go ahead with this issue. 
If any details are required, feel free to ask.
I'm assigning it to you.

Apologies for late reply.

**Comment by the-amazing-atharva** [comment]
No worries!!

Working on it in smtm
